---


- name: Install PHP Packages
  apt: name={{ item }} state=present
  with_items:
      - libapache2-mod-php
      - php
      - php-mysql
      - php-mcrypt
      - php-cli
      - php-cgi
      - php-curl
      - php-gd
      - php-intl
      - php-json
      - php-mbstring
      - php-opcache
      - php-readline
      - php-xml
      - php-xsl
      - php-zip
      - php-bz2
      - php-gmp
      - php-igbinary
      - php-imagick
      - php-pspell
      - php-common
  notify:
    - restart apache2

- name: Configure memory_limit
  lineinfile:
    dest: /etc/php/7.0/apache2/php.ini
    regexp: '^memory_limit'
    line: 'memory_limit = 256M'
    backrefs: yes
  notify:
    - restart apache2
